### ISSUE TITLE
Error in dev mode - location is not defined

### ISSUE THREAD

**Issue by luisFilipePT** [luisFilipePT/shadcn-ui-theme-explorer#6]
Fix the error described :) 

```bash
- error node_modules/next/dist/client/components/app-router.js (144:65) @ location
- error ReferenceError: location is not defined
    at useSetTheme (./hooks/use-set-theme.ts:25:16)
    at ThemeArrows (./components/theme-arrows.tsx:21:70)
null
- error node_modules/next/dist/client/components/app-router.js (144:65) @ location
- error ReferenceError: location is not defined
    at useSetTheme (./hooks/use-set-theme.ts:25:16)
    at ThemeArrows (./components/theme-arrows.tsx:21:70)
null
```

**Comment by Tk-brainCodes** [comment]
Hi @luisFilipePT, i would love to resolve this error. It has do with location not being recognized on the server-side, so it has to be specified to be used only on the client-side

**Comment by luisFilipePT** [comment]
> Hi @luisFilipePT, i would love to resolve this error. It has do with location not being recognized on the server-side, so it has to be specified to be used only on the client-side

Give it a go 😉 and thanks for the help, open a PR when you think it's ready for review and tag me.

In the meantime if you need anything just comment here and tag me or @joanamcsa
